README.md
Seiga em frente, olhe para o lado...
=> Carreta Furacão

README.md
=> E o bambu #13

README.md
Hide your kids, hide your wife...
=> Add bed intruder song

README.md
=> Add hokuto

README.md
=> Add "Tava ruim agora parece que piorou"

README.md
Além de adicionar thumbnails, troquei alguns links e imagem.
=> Adicionando thumbnails

README.md
Incrementação de 3 novos memes e alteração nas imagens, passando os .jpg pra .gif
=> Animando as coisas

README.md
tarefa  https://github.com/ocarneiro/para-entender-a-internet/issues/12
=> Xuxa claudia

README.md
Marcio canuto, famoso reporter brasileiro, entrevista garotinho que fica nervoso ao achar que foi chamado de cachorro!
- e você pequenininho, quando ver um dinossauro tão grande que que se achou???
- cachorro? Que cachorro oque? Eu não sou cachorro não...!!﻿
=> Cachorro? Que cachorro o que! Eu não sou cachorro não!

English.md
=> Versão em Inglês 

README.md
Novos memes adicionados! E este é meu primeiro PR wooooWWWW
=> Eita giovana, eu quero café!

README.md
Então aceita o pull de primeira :laughing:
=> Adicionar Deus é top - Tweets do Neymar

README.md, _config.yml
Foram incrementados 4 memes:
- Como você é burro cara!
- Quero café
- Para nossa alegria
- Nissim Ourfali
Substituição de alguns .jpg para .gif
=> Adicionando memes e Atualizando Gifs

README.md
aceita ai mano, depois dou uma melhorada
=> adcionando meme

README.md
Adicionei o vídeo do King Size de Niterói, Rei Maior do Rio de Janeiro, Senhor das Barcas.
=> King Size de Niterói

README.md
Adição de meme travolta ao readme file
=> Adicionando Meme Travolta Confused

README.md
Eu sou rolezeiro e adicionei um vídeo de uma galera muitus brutus
=> Bora fechar?

README.md
Adicionando o meme otaku Za Warudo
Explicando o meme ( http://knowyourmeme.com/memes/za-warudo-wryyyyy )
=> Adicionando MEME

README.md
Parabéns para o importante trabalho para a internet brasileira, e porque não dizer, para a rede mundial como um todo.
Acrescentei o meme do sanduíche-iche.
=> Adicionando meme do sanduíche-iche

README.md
Votei nela, mas nessas é pra rir, XD
=> Meme da Dilma

README.md
Um cara gentil aqui do Nordeste
=> Meme do Seu Lunga

README.md
Mais uma vez nosso heroi mexicano expõe sua sabedoria assaz aprazível
=> Meme do Chapolin Sincero

README.md
=> Outro meme do nosso Chapolin!

README.md
=> Add meme Vinicius Jr cantando pagode

README.md
Adicionando o famoso poeta Galo Cego, que nos agracia com suas belas filosofias de vida.
=> Add Galo Cego

README.md
Meme "Você acredita em simpatia?
=> Adicionando meme "Você acredita em simpatia?"

README.md
Meme "Quem não gosta, gosta, quem não gosta, curte"
=> Adicionando meme "Quem não gosta, gosta"

README.md
Maurilio do choque de cultura dando boa noite para os amantes da sétima arte
=> Maurílio - boa noite

README.md
Adicionando esse meme que eu acho fantástico e necessário nas conversas do dia a dia.
=> Add meme dia de rock bebe

README.md
Melhor meme para atazanar as amigas!!
=> adiciona meme Mas cê ta brava?

README.md
Adicionando meme da Pabllo Vittar contando sobre brigas nos shows dela no programa do Eduardo Sterblitch.
=> Adicionando meme "DJ para o som"

README.md
Meme que evidencia todo potencial de Bolsonaro como atleta brasileiro. Uma belíssima imitação de pombo comendo pipoca. :]
=> add meme flexões do presidente atleta

README.md
Adicionei um meme a mais, além de ser algo divertido é um treinamento para o Hacktoberfest :) 
Peço perdão pela correção automática... onde está escrito "boilerplate" na verdade era pra ser "bilete"... erro de iniciante hahahaha
parabéns pelo projeto!!
=> add new meme 'É verdade esse bilete'

README.md
Meme vindo da Jéssica no vídeo do Porta dos Fundos
=> Adiciona meme "Tava tudo meio médio, agora tá tudo meio merda"
